// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: bobadojo/stores/v1/stores.proto

package storespb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A store.
type Store struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique id (e.g. store number)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// An identifier indicating the type of store
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// Store name (human-readable)
	Title string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	// Store location
	Location *Location `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	// Store address
	Address *Address `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	// Store hours
	StoreHours    string `protobuf:"bytes,8,opt,name=store_hours,json=storeHours,proto3" json:"store_hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_bobadojo_stores_v1_stores_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_bobadojo_stores_v1_stores_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_bobadojo_stores_v1_stores_proto_rawDescGZIP(), []int{0}
}

func (x *Store) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Store) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Store) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Store) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Store) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Store) GetStoreHours() string {
	if x != nil {
		return x.StoreHours
	}
	return ""
}

// An address.
type Address struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Street address
	Street string `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	// City
	City string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	// State
	State string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	// Zip code
	ZipCode int32 `protobuf:"varint,4,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	// Country
	RegionCode string `protobuf:"bytes,5,opt,name=region_code,json=regionCode,proto3" json:"region_code,omitempty"`
	// County
	County        string `protobuf:"bytes,6,opt,name=county,proto3" json:"county,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_bobadojo_stores_v1_stores_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_bobadojo_stores_v1_stores_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_bobadojo_stores_v1_stores_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetZipCode() int32 {
	if x != nil {
		return x.ZipCode
	}
	return 0
}

func (x *Address) GetRegionCode() string {
	if x != nil {
		return x.RegionCode
	}
	return ""
}

func (x *Address) GetCounty() string {
	if x != nil {
		return x.County
	}
	return ""
}

// A location in terrestrial coordinates.
type Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Latitude of the location.
	Latitude float32 `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// Longitude of the location.
	Longitude     float32 `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_bobadojo_stores_v1_stores_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_bobadojo_stores_v1_stores_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_bobadojo_stores_v1_stores_proto_rawDescGZIP(), []int{2}
}

func (x *Location) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// A bounding box in terrestrial coordinates.
type BoundingBox struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum coordinate values.
	Max *Location `protobuf:"bytes,1,opt,name=max,proto3" json:"max,omitempty"`
	// Minimum coordinate values.
	Min           *Location `protobuf:"bytes,2,opt,name=min,proto3" json:"min,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_bobadojo_stores_v1_stores_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_bobadojo_stores_v1_stores_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_bobadojo_stores_v1_stores_proto_rawDescGZIP(), []int{3}
}

func (x *BoundingBox) GetMax() *Location {
	if x != nil {
		return x.Max
	}
	return nil
}

func (x *BoundingBox) GetMin() *Location {
	if x != nil {
		return x.Min
	}
	return nil
}

// Request to FindStores.
type FindStoresRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bounding box of the request.
	Bounds *BoundingBox `protobuf:"bytes,1,opt,name=bounds,proto3" json:"bounds,omitempty"`
	// Maximum number of results to return.
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindStoresRequest) Reset() {
	*x = FindStoresRequest{}
	mi := &file_bobadojo_stores_v1_stores_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindStoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindStoresRequest) ProtoMessage() {}

func (x *FindStoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bobadojo_stores_v1_stores_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindStoresRequest.ProtoReflect.Descriptor instead.
func (*FindStoresRequest) Descriptor() ([]byte, []int) {
	return file_bobadojo_stores_v1_stores_proto_rawDescGZIP(), []int{4}
}

func (x *FindStoresRequest) GetBounds() *BoundingBox {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *FindStoresRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Response from FindStores.
type FindStoresResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of matching stores.
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// Matching stores.
	Stores        []*Store `protobuf:"bytes,2,rep,name=stores,proto3" json:"stores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindStoresResponse) Reset() {
	*x = FindStoresResponse{}
	mi := &file_bobadojo_stores_v1_stores_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindStoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindStoresResponse) ProtoMessage() {}

func (x *FindStoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bobadojo_stores_v1_stores_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindStoresResponse.ProtoReflect.Descriptor instead.
func (*FindStoresResponse) Descriptor() ([]byte, []int) {
	return file_bobadojo_stores_v1_stores_proto_rawDescGZIP(), []int{5}
}

func (x *FindStoresResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FindStoresResponse) GetStores() []*Store {
	if x != nil {
		return x.Stores
	}
	return nil
}

// Request to GetStore.
type GetStoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the store resource to retrieve.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreRequest) Reset() {
	*x = GetStoreRequest{}
	mi := &file_bobadojo_stores_v1_stores_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreRequest) ProtoMessage() {}

func (x *GetStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bobadojo_stores_v1_stores_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreRequest.ProtoReflect.Descriptor instead.
func (*GetStoreRequest) Descriptor() ([]byte, []int) {
	return file_bobadojo_stores_v1_stores_proto_rawDescGZIP(), []int{6}
}

func (x *GetStoreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request to ListStores.
type ListStoresRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page size.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Pagination token.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoresRequest) Reset() {
	*x = ListStoresRequest{}
	mi := &file_bobadojo_stores_v1_stores_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoresRequest) ProtoMessage() {}

func (x *ListStoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bobadojo_stores_v1_stores_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoresRequest.ProtoReflect.Descriptor instead.
func (*ListStoresRequest) Descriptor() ([]byte, []int) {
	return file_bobadojo_stores_v1_stores_proto_rawDescGZIP(), []int{7}
}

func (x *ListStoresRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListStoresRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Response from ListStores.
type ListStoresResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of stores.
	Stores []*Store `protobuf:"bytes,1,rep,name=stores,proto3" json:"stores,omitempty"`
	// Token of next page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoresResponse) Reset() {
	*x = ListStoresResponse{}
	mi := &file_bobadojo_stores_v1_stores_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoresResponse) ProtoMessage() {}

func (x *ListStoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bobadojo_stores_v1_stores_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoresResponse.ProtoReflect.Descriptor instead.
func (*ListStoresResponse) Descriptor() ([]byte, []int) {
	return file_bobadojo_stores_v1_stores_proto_rawDescGZIP(), []int{8}
}

func (x *ListStoresResponse) GetStores() []*Store {
	if x != nil {
		return x.Stores
	}
	return nil
}

func (x *ListStoresResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_bobadojo_stores_v1_stores_proto protoreflect.FileDescriptor

const file_bobadojo_stores_v1_stores_proto_rawDesc = "" +
	"\n" +
	"\x1fbobadojo/stores/v1/stores.proto\x12\x12bobadojo.stores.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\x9a\x02\n" +
	"\x05Store\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x128\n" +
	"\blocation\x18\x06 \x01(\v2\x1c.bobadojo.stores.v1.LocationR\blocation\x125\n" +
	"\aaddress\x18\a \x01(\v2\x1b.bobadojo.stores.v1.AddressR\aaddress\x12\x1f\n" +
	"\vstore_hours\x18\b \x01(\tR\n" +
	"storeHours:<\xeaA9\n" +
	"\x18stores.bobadojo.io/Store\x12\x0estores/{store}*\x06stores2\x05store\"\x9f\x01\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x19\n" +
	"\bzip_code\x18\x04 \x01(\x05R\azipCode\x12\x1f\n" +
	"\vregion_code\x18\x05 \x01(\tR\n" +
	"regionCode\x12\x16\n" +
	"\x06county\x18\x06 \x01(\tR\x06county\"N\n" +
	"\bLocation\x12\x1f\n" +
	"\blatitude\x18\x01 \x01(\x02B\x03\xe0A\x02R\blatitude\x12!\n" +
	"\tlongitude\x18\x02 \x01(\x02B\x03\xe0A\x02R\tlongitude\"w\n" +
	"\vBoundingBox\x123\n" +
	"\x03max\x18\x01 \x01(\v2\x1c.bobadojo.stores.v1.LocationB\x03\xe0A\x02R\x03max\x123\n" +
	"\x03min\x18\x02 \x01(\v2\x1c.bobadojo.stores.v1.LocationB\x03\xe0A\x02R\x03min\"l\n" +
	"\x11FindStoresRequest\x12<\n" +
	"\x06bounds\x18\x01 \x01(\v2\x1f.bobadojo.stores.v1.BoundingBoxB\x03\xe0A\x02R\x06bounds\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05B\x03\xe0A\x01R\x05limit\"]\n" +
	"\x12FindStoresResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x121\n" +
	"\x06stores\x18\x02 \x03(\v2\x19.bobadojo.stores.v1.StoreR\x06stores\"H\n" +
	"\x0fGetStoreRequest\x125\n" +
	"\x04name\x18\x01 \x01(\tB!\xe0A\x02\xfaA\x1b\n" +
	"\x19stores.bobadojo.com/StoreR\x04name\"Y\n" +
	"\x11ListStoresRequest\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x03\xe0A\x01R\tpageToken\"o\n" +
	"\x12ListStoresResponse\x121\n" +
	"\x06stores\x18\x01 \x03(\v2\x19.bobadojo.stores.v1.StoreR\x06stores\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xdf\x02\n" +
	"\x06Stores\x12o\n" +
	"\n" +
	"ListStores\x12%.bobadojo.stores.v1.ListStoresRequest\x1a&.bobadojo.stores.v1.ListStoresResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/stores\x12t\n" +
	"\n" +
	"FindStores\x12%.bobadojo.stores.v1.FindStoresRequest\x1a&.bobadojo.stores.v1.FindStoresResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/stores:find\x12n\n" +
	"\bGetStore\x12#.bobadojo.stores.v1.GetStoreRequest\x1a\x19.bobadojo.stores.v1.Store\"\"\xdaA\x04name\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/{name=stores/*}B_\n" +
	"\x16com.bobadojo.stores.v1B\vStoresProtoP\x01Z6github.com/bobadojo/go/pkg/stores/v1/storespb;storespbb\x06proto3"

var (
	file_bobadojo_stores_v1_stores_proto_rawDescOnce sync.Once
	file_bobadojo_stores_v1_stores_proto_rawDescData []byte
)

func file_bobadojo_stores_v1_stores_proto_rawDescGZIP() []byte {
	file_bobadojo_stores_v1_stores_proto_rawDescOnce.Do(func() {
		file_bobadojo_stores_v1_stores_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bobadojo_stores_v1_stores_proto_rawDesc), len(file_bobadojo_stores_v1_stores_proto_rawDesc)))
	})
	return file_bobadojo_stores_v1_stores_proto_rawDescData
}

var file_bobadojo_stores_v1_stores_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bobadojo_stores_v1_stores_proto_goTypes = []any{
	(*Store)(nil),              // 0: bobadojo.stores.v1.Store
	(*Address)(nil),            // 1: bobadojo.stores.v1.Address
	(*Location)(nil),           // 2: bobadojo.stores.v1.Location
	(*BoundingBox)(nil),        // 3: bobadojo.stores.v1.BoundingBox
	(*FindStoresRequest)(nil),  // 4: bobadojo.stores.v1.FindStoresRequest
	(*FindStoresResponse)(nil), // 5: bobadojo.stores.v1.FindStoresResponse
	(*GetStoreRequest)(nil),    // 6: bobadojo.stores.v1.GetStoreRequest
	(*ListStoresRequest)(nil),  // 7: bobadojo.stores.v1.ListStoresRequest
	(*ListStoresResponse)(nil), // 8: bobadojo.stores.v1.ListStoresResponse
}
var file_bobadojo_stores_v1_stores_proto_depIdxs = []int32{
	2,  // 0: bobadojo.stores.v1.Store.location:type_name -> bobadojo.stores.v1.Location
	1,  // 1: bobadojo.stores.v1.Store.address:type_name -> bobadojo.stores.v1.Address
	2,  // 2: bobadojo.stores.v1.BoundingBox.max:type_name -> bobadojo.stores.v1.Location
	2,  // 3: bobadojo.stores.v1.BoundingBox.min:type_name -> bobadojo.stores.v1.Location
	3,  // 4: bobadojo.stores.v1.FindStoresRequest.bounds:type_name -> bobadojo.stores.v1.BoundingBox
	0,  // 5: bobadojo.stores.v1.FindStoresResponse.stores:type_name -> bobadojo.stores.v1.Store
	0,  // 6: bobadojo.stores.v1.ListStoresResponse.stores:type_name -> bobadojo.stores.v1.Store
	7,  // 7: bobadojo.stores.v1.Stores.ListStores:input_type -> bobadojo.stores.v1.ListStoresRequest
	4,  // 8: bobadojo.stores.v1.Stores.FindStores:input_type -> bobadojo.stores.v1.FindStoresRequest
	6,  // 9: bobadojo.stores.v1.Stores.GetStore:input_type -> bobadojo.stores.v1.GetStoreRequest
	8,  // 10: bobadojo.stores.v1.Stores.ListStores:output_type -> bobadojo.stores.v1.ListStoresResponse
	5,  // 11: bobadojo.stores.v1.Stores.FindStores:output_type -> bobadojo.stores.v1.FindStoresResponse
	0,  // 12: bobadojo.stores.v1.Stores.GetStore:output_type -> bobadojo.stores.v1.Store
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_bobadojo_stores_v1_stores_proto_init() }
func file_bobadojo_stores_v1_stores_proto_init() {
	if File_bobadojo_stores_v1_stores_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bobadojo_stores_v1_stores_proto_rawDesc), len(file_bobadojo_stores_v1_stores_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bobadojo_stores_v1_stores_proto_goTypes,
		DependencyIndexes: file_bobadojo_stores_v1_stores_proto_depIdxs,
		MessageInfos:      file_bobadojo_stores_v1_stores_proto_msgTypes,
	}.Build()
	File_bobadojo_stores_v1_stores_proto = out.File
	file_bobadojo_stores_v1_stores_proto_goTypes = nil
	file_bobadojo_stores_v1_stores_proto_depIdxs = nil
}
