// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go_gapic. DO NOT EDIT.


package gapic

import (
	"context"
	"fmt"
	"math"
	"net/url"

	menuspb "github.com/bobadojo/go/pkg/menus/v1/menuspb"
	gax "github.com/googleapis/gax-go/v2"
	"google.golang.org/api/option"
	"google.golang.org/api/option/internaloption"
	gtransport "google.golang.org/api/transport/grpc"
	"google.golang.org/grpc"
)

var newMenusClientHook clientHook

// MenusCallOptions contains the retry settings for each method of MenusClient.
type MenusCallOptions struct {
	GetMenu []gax.CallOption
}

func defaultMenusGRPCClientOptions() []option.ClientOption {
	return []option.ClientOption{
		internaloption.WithDefaultEndpoint(":443"),
		internaloption.WithDefaultEndpointTemplate(":443"),
		internaloption.WithDefaultMTLSEndpoint(":443"),
		internaloption.WithDefaultUniverseDomain("googleapis.com"),
		internaloption.WithDefaultAudience("https://"),
		internaloption.WithDefaultScopes(DefaultAuthScopes()...),
		internaloption.EnableJwtWithScope(),
		internaloption.EnableNewAuthLibrary(),
		option.WithGRPCDialOption(grpc.WithDefaultCallOptions(
		grpc.MaxCallRecvMsgSize(math.MaxInt32))),
	}
}

func defaultMenusCallOptions() *MenusCallOptions {
	return &MenusCallOptions{
		GetMenu: []gax.CallOption{
		},
	}
}

// internalMenusClient is an interface that defines the methods available from .
type internalMenusClient interface {
	Close() error
	setGoogleClientInfo(...string)
	Connection() *grpc.ClientConn
	GetMenu(context.Context, *menuspb.GetMenuRequest, ...gax.CallOption) (*menuspb.Menu, error)
}

// MenusClient is a client for interacting with .
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
//
// Get information about store menus.
type MenusClient struct {
	// The internal transport-dependent client.
	internalClient internalMenusClient

	// The call options for this service.
	CallOptions *MenusCallOptions

}

// Wrapper methods routed to the internal client.

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *MenusClient) Close() error {
	return c.internalClient.Close()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *MenusClient) setGoogleClientInfo(keyval ...string) {
	c.internalClient.setGoogleClientInfo(keyval...)
}

// Connection returns a connection to the API service.
//
// Deprecated: Connections are now pooled so this method does not always
// return the same resource.
func (c *MenusClient) Connection() *grpc.ClientConn {
	return c.internalClient.Connection()
}

// GetMenu returns a menu for a specific store.
func (c *MenusClient) GetMenu(ctx context.Context, req *menuspb.GetMenuRequest, opts ...gax.CallOption) (*menuspb.Menu, error) {
	return c.internalClient.GetMenu(ctx, req, opts...)
}

// menusGRPCClient is a client for interacting with  over gRPC transport.
//
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
type menusGRPCClient struct {
	// Connection pool of gRPC connections to the service.
	connPool gtransport.ConnPool

	// Points back to the CallOptions field of the containing MenusClient
	CallOptions **MenusCallOptions

	// The gRPC API client.
	menusClient menuspb.MenusClient

	// The x-goog-* metadata to be sent with each request.
	xGoogHeaders []string
}

// NewMenusClient creates a new menus client based on gRPC.
// The returned client must be Closed when it is done being used to clean up its underlying connections.
//
// Get information about store menus.
func NewMenusClient(ctx context.Context, opts ...option.ClientOption) (*MenusClient, error) {
	clientOpts := defaultMenusGRPCClientOptions()
	if newMenusClientHook != nil {
		hookOpts, err := newMenusClientHook(ctx, clientHookParams{})
		if err != nil {
			return nil, err
		}
		clientOpts = append(clientOpts, hookOpts...)
	}

	connPool, err := gtransport.DialPool(ctx, append(clientOpts, opts...)...)
	if err != nil {
		return nil, err
	}
	client := MenusClient{CallOptions: defaultMenusCallOptions()}

	c := &menusGRPCClient{
		connPool:    connPool,
		menusClient: menuspb.NewMenusClient(connPool),
		CallOptions: &client.CallOptions,

	}
	c.setGoogleClientInfo()

	client.internalClient = c

	return &client, nil
}

// Connection returns a connection to the API service.
//
// Deprecated: Connections are now pooled so this method does not always
// return the same resource.
func (c *menusGRPCClient) Connection() *grpc.ClientConn {
	return c.connPool.Conn()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *menusGRPCClient) setGoogleClientInfo(keyval ...string) {
	kv := append([]string{"gl-go", gax.GoVersion}, keyval...)
	kv = append(kv, "gapic", getVersionClient(), "gax", gax.Version, "grpc", grpc.Version)
	c.xGoogHeaders = []string{
		"x-goog-api-client", gax.XGoogHeader(kv...),
	}
}

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *menusGRPCClient) Close() error {
	return c.connPool.Close()
}

func (c *menusGRPCClient) GetMenu(ctx context.Context, req *menuspb.GetMenuRequest, opts ...gax.CallOption) (*menuspb.Menu, error) {
	hds := []string{"x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName()))}

	hds = append(c.xGoogHeaders, hds...)
	ctx = gax.InsertMetadataIntoOutgoingContext(ctx, hds...)
	opts = append((*c.CallOptions).GetMenu[0:len((*c.CallOptions).GetMenu):len((*c.CallOptions).GetMenu)], opts...)
	var resp *menuspb.Menu
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.menusClient.GetMenu(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
