// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: bobadojo/menus/v1/menus.proto

package menuspb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to GetMenu.
type GetMenuRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the menu resource to retrieve.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuRequest) Reset() {
	*x = GetMenuRequest{}
	mi := &file_bobadojo_menus_v1_menus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuRequest) ProtoMessage() {}

func (x *GetMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bobadojo_menus_v1_menus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuRequest.ProtoReflect.Descriptor instead.
func (*GetMenuRequest) Descriptor() ([]byte, []int) {
	return file_bobadojo_menus_v1_menus_proto_rawDescGZIP(), []int{0}
}

func (x *GetMenuRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// A store resource.
type Menu struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique id.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// A description of the menu
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_bobadojo_menus_v1_menus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_bobadojo_menus_v1_menus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_bobadojo_menus_v1_menus_proto_rawDescGZIP(), []int{1}
}

func (x *Menu) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Menu) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_bobadojo_menus_v1_menus_proto protoreflect.FileDescriptor

const file_bobadojo_menus_v1_menus_proto_rawDesc = "" +
	"\n" +
	"\x1dbobadojo/menus/v1/menus.proto\x12\x11bobadojo.menus.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"E\n" +
	"\x0eGetMenuRequest\x123\n" +
	"\x04name\x18\x01 \x01(\tB\x1f\xe0A\x02\xfaA\x19\n" +
	"\x17menus.bobadojo.com/MenuR\x04name\"B\n" +
	"\x04Menu\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\x12%\n" +
	"\vdescription\x18\x02 \x01(\tB\x03\xe0A\x01R\vdescription2u\n" +
	"\x05Menus\x12l\n" +
	"\aGetMenu\x12!.bobadojo.menus.v1.GetMenuRequest\x1a\x17.bobadojo.menus.v1.Menu\"%\xdaA\x04name\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/menus/{name=store}BZ\n" +
	"\x15com.bobadojo.menus.v1B\n" +
	"MenusProtoP\x01Z3github.com/bobadojo/go/pkg/menus/v1/menuspb;menuspbb\x06proto3"

var (
	file_bobadojo_menus_v1_menus_proto_rawDescOnce sync.Once
	file_bobadojo_menus_v1_menus_proto_rawDescData []byte
)

func file_bobadojo_menus_v1_menus_proto_rawDescGZIP() []byte {
	file_bobadojo_menus_v1_menus_proto_rawDescOnce.Do(func() {
		file_bobadojo_menus_v1_menus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bobadojo_menus_v1_menus_proto_rawDesc), len(file_bobadojo_menus_v1_menus_proto_rawDesc)))
	})
	return file_bobadojo_menus_v1_menus_proto_rawDescData
}

var file_bobadojo_menus_v1_menus_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bobadojo_menus_v1_menus_proto_goTypes = []any{
	(*GetMenuRequest)(nil), // 0: bobadojo.menus.v1.GetMenuRequest
	(*Menu)(nil),           // 1: bobadojo.menus.v1.Menu
}
var file_bobadojo_menus_v1_menus_proto_depIdxs = []int32{
	0, // 0: bobadojo.menus.v1.Menus.GetMenu:input_type -> bobadojo.menus.v1.GetMenuRequest
	1, // 1: bobadojo.menus.v1.Menus.GetMenu:output_type -> bobadojo.menus.v1.Menu
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bobadojo_menus_v1_menus_proto_init() }
func file_bobadojo_menus_v1_menus_proto_init() {
	if File_bobadojo_menus_v1_menus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bobadojo_menus_v1_menus_proto_rawDesc), len(file_bobadojo_menus_v1_menus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bobadojo_menus_v1_menus_proto_goTypes,
		DependencyIndexes: file_bobadojo_menus_v1_menus_proto_depIdxs,
		MessageInfos:      file_bobadojo_menus_v1_menus_proto_msgTypes,
	}.Build()
	File_bobadojo_menus_v1_menus_proto = out.File
	file_bobadojo_menus_v1_menus_proto_goTypes = nil
	file_bobadojo_menus_v1_menus_proto_depIdxs = nil
}
